typography_spectrum: 0.40211535687558353
color:
  brandColors:
    - '#F6F792'
    - '#333745'
    - '#77C4D3'
    - '#DAEDE2'
    - '#EA2E49'
  brandStrength: 0.2577422200702131
  lightness: 0.09443324571475387
  saturation: 0.4885132201015949
  rhythmicContrast: 0.8636579839512706
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.46042799740098417
analytics:
  google: UA-5050578-6
  facebook: null
  twitter: null
author:
  name: Claudio Raimondi
name: Claudio Raimondi
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: LinkedIn
    url: 'http://linkedin.com/in/craimondi'
    type: external
  - name: Twitter
    url: 'http://www.twitter.com/ClaudioRaimondi'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Claudio Raimondi
description: TEST
purpose: []
