analytics:
  twitter: null
  google: UA-5050578-6
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.63885
title: Claudio Raimondi Online
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 1
  brandStrength: 0
  rhythmicContrast: 1
  brandColors:
    - '#f5fafa'
    - '#c1dad6'
    - '#6d929b'
    - '#b7afa3'
    - '#e8d0a9'
  lightness: 0.625
purpose: []
favicon: null
name: Claudio Raimondi
typography_spectrum: 0.74931
