layout_spectrum: 0.07714837114326656
typography_spectrum: 0.7485397916752845
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.1100810517091304
  lightness: 0.8925250759348273
  saturation: 0.11341641005128622
  rhythmicContrast: 0.907411489635706
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/589045e1-797f-4222-b7b2-e03ae0966097.jpg
  type: null
  appId: '288651771490588'
analytics:
  google: UA-5050578-6
  facebook: null
  twitter: null
author:
  name: Claudio Raimondi
  url: www.ClaudioRaimondi.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b3a49c81-c304-436f-a3ca-2500b22a0665.jpg
name: Claudio Raimondi
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: blog
    url: 'http://www.ClaudioRaimondi.com'
    type: external
  - name: press
    url: 'http://press.ClaudioRaimondi.com'
    type: external
  - name: about  me
    id: 9a310db8-471e-475d-8ab1-52b7af6069d1
    type: content
  - name: on Twitter
    url: 'http://www.twitter.com/ClaudioRaimondi'
    type: external
  - name: on LinkedIn
    url: 'https://www.linkedin.com/in/craimondi'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3e9da336-8579-432a-adcc-304b541551c5.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: BLOG
description: 'Claudio Raimondi, General Manager at eBay in Italy'
purpose: []
