typography_spectrum: 0.7208443060517311
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.5625
  rhythmicContrast: 0.25
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/589045e1-797f-4222-b7b2-e03ae0966097.jpg
  type: null
  appId: '288651771490588'
layout_spectrum: 0.8719011719804257
analytics:
  google: UA-5050578-6
  facebook: null
  twitter: null
author:
  name: Claudio Raimondi
  url: 'http://www.ClaudioRaimondi.com'
  email: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b3a49c81-c304-436f-a3ca-2500b22a0665.jpg
name: blog
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Claudio Raimondi
    id: 0ddfb149-be62-49bb-a17c-56a2dc5c6417
    type: content
  - name: press
    url: 'http://press.ClaudioRaimondi.com'
    type: external
  - name: on Twitter
    url: 'http://www.twitter.com/ClaudioRaimondi'
    type: external
  - name: on LinkedIn
    url: 'https://www.linkedin.com/in/craimondi'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3e9da336-8579-432a-adcc-304b541551c5.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: BLOG
description: BLOG
purpose: []
