name: Claudio Raimondi
favicon: null
layout_spectrum: 0.90951
typography_spectrum: 0.48216
title: Claudio Raimondi Online
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-5050578-6
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ecf0f3'
    - '#363a57'
    - '#aa8e85'
    - '#b8da87'
    - '#adbcde'
  brandStrength: 0
  lightness: 0.8094667168334126
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
