typography_spectrum: 0.40211535687558353
color:
  brandColors:
    - '#F6F792'
    - '#333745'
    - '#77C4D3'
    - '#DAEDE2'
    - '#EA2E49'
  brandStrength: 0.2577422200702131
  lightness: 0.09443324571475387
  saturation: 0.4885132201015949
  rhythmicContrast: 0.8636579839512706
opengraph:
  image: null
  type: null
  appId: '288651771490588'
layout_spectrum: 0.46042799740098417
analytics:
  google: UA-5050578-6
  facebook: '260942680957678'
  twitter: >-
    !function(e,n,u,a){e.twq||(a=e.twq=function(){a.exe?a.exe.apply(a,arguments):
    a.queue.push(arguments);},a.version='1',a.queue=[],t=n.createElement(u),
    t.async=!0,t.src='//static.ads-twitter.com/uwt.js',s=n.getElementsByTagName(u)[0],
    s.parentNode.insertBefore(t,s))}(window,document,'script'); // Insert
    Twitter Pixel ID and Standard Event data below twq('init','nvaic');
    twq('track','PageView');
author:
  name: Claudio Raimondi
  url: www.ClaudioRaimondi.com
name: 'Claudio Raimondi, General Manager at eBay in Italy'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: LinkedIn
    url: 'http://linkedin.com/in/craimondi'
    type: external
  - name: Twitter
    url: 'http://www.twitter.com/ClaudioRaimondi'
    type: external
  - name: ABOUT ME
    id: b93bab99-972b-4f98-8547-34e84171f075
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Claudio Raimondi
description: HUB
purpose: []
