title: CR
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: HUB
color:
  saturation: 0.4817401
  brandStrength: 0.6348021302837878
  lightness: 0.7513427
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  rhythmicContrast: 0.8641245
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: >-
    !function(e,n,u,a){e.twq||(a=e.twq=function(){a.exe?a.exe.apply(a,arguments):
    a.queue.push(arguments);},a.version='1',a.queue=[],t=n.createElement(u),
    t.async=!0,t.src='//static.ads-twitter.com/uwt.js',s=n.getElementsByTagName(u)[0],
    s.parentNode.insertBefore(t,s))}(window,document,'script'); // Insert
    Twitter Pixel ID and Standard Event data below twq('init','nvaic');
    twq('track','PageView');
  google: UA-5050578-6
  facebook: '260942680957678'
favicon: null
author:
  name: Claudio Raimondi
  url: www.ClaudioRaimondi.com
name: 'Claudio Raimondi, General Manager at eBay in Italy'
opengraph:
  image: null
  type: null
  appId: '288651771490588'
navigation:
  - name: LinkedIn
    url: 'http://linkedin.com/in/craimondi'
    type: external
  - name: Twitter
    url: 'http://www.twitter.com/ClaudioRaimondi'
    type: external
typography_spectrum: 0.4570354
layout_spectrum: 0.4677766
