typography_spectrum: 0.4570354
color:
  saturation: 0.4817401
  brandStrength: 0.7567132
  lightness: 0.7513427
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  rhythmicContrast: 0.566595
opengraph:
  image: null
  type: null
  appId: '288651771490588'
layout_spectrum: 0.679377
analytics:
  twitter: null
  google: UA-5050578-6
  facebook: '260942680957678'
author:
  name: Claudio Raimondi
  url: www.ClaudioRaimondi.com
name: 'Claudio Raimondi, General Manager at eBay in Italy'
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: BLOG
    url: 'http://www.ClaudioRaimondi.com'
    type: external
  - name: PRESS
    url: 'http://press.ClaudioRaimondi.com'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Claudio Raimondi
description: HUB
purpose: []
